### ISSUE TITLE
Fail to install "IUCNN" from GitHub

### ISSUE THREAD

**Issue by PabloMLucas** [IUCNN/IUCNN#43]
Error when trying to install the package using    install_github("IUCNN/IUCNN")

Error: Failed to install 'IUCNN' from GitHub:
  Multiple results for CXX11FLAGS found, something is wrong.FALSE

**Comment by azizka** [comment]
OK, I could not reproduce this error, but fixed some remaining issues with the function namespace. It is working for me now. Please try again

**Comment by PabloMLucas** [comment]
Thanks Alexander, threre was a strange problem in my computer, I had this error and then I checked in my laptop and I could install it perfectly. I found that it was an error with the file "Makevars.win" which had some kind of duplicates. I opened it and edit manually removing the duplicates using  file.edit(file.path(Sys.getenv("HOME"), ".R", "Makevars.win"))  

A similar error can occurs for Stan/windows Issue #866
https://github.com/stan-dev/rstan/issues/866

Now it is working perfectly, thanks
