### ISSUE TITLE
Warning message when using "iucnn_feature_importance"

### ISSUE THREAD

**Issue by PabloMLucas** [IUCNN/IUCNN#44]
I am using the function "iucnn_feature_importance" with custom features in order to have the importance of each variable (not block of variables). I obtain a warning message:
"Warning message:
In iucnn_feature_importance(x = m_prod, feature_blocks = list(c(m_prod$input_data$feature_names)),  :
  NAs introduced by coercion"

I don´t know what happens but I obtain a list of my feature names plus one more feature with a name NA in the name, maybe I am not understanding or forgetting something. I would thanks a feedback about this. Thanks in advance.

          # Train the best model on all training data for prediction
          m_prod <- iucnn_train_model(x = features,
            lab = labels_train,
            production_model = m_best,
            overwrite=TRUE)
          #Importance for each variable custom
          imp_cust <- iucnn_feature_importance(x = m_prod,
            feature_blocks = list(c(m_prod$ input_data$ feature_names)),
            provide_indices = TRUE)

**Comment by tandermann** [comment]
Each feature should be it's own block in this case. So you need to provide a list of lists so to say. Try to provide `as.list(c(m1$ input_data$ feature_names))` as input instead (instead of using `list()`) , that command formats the feature_blocks input correctly.
Does that work for you?
