### ISSUE TITLE
The standard for selecting the optimal models

### ISSUE THREAD

**Issue by Orange-chen-PEAR** [IUCNN/IUCNN#50]
Hi @ALL,

I had some trouble with the application of IUCNN. In selecting the optimal models between the classification models and the regression models using IUCNN, can we use validation loss as the standard? If we can, would you mind explaining the principle of the calculation of validation loss?

Can you help me with this?
Thank you for your kind consideration of this request.

Jinnan

**Comment by azizka** [comment]
@tandermann
