### ISSUE TITLE
Which field in the output of the bnn-class model (.log) indicates the posterior probability

### ISSUE THREAD

**Issue by Orange-chen-PEAR** [IUCNN/IUCNN#51]
Hi all,
I am confused when interpreting the model output file (.log). Which field in the bnn-class model output (.log) indicates the posterior probability? How do I calculate the effective sample size of the posterior probability?

Can you help me with this?
@azizka @dsilvestro @Rekyt @tandermann 
![cb4922bf91fae879f73792f8afd73a8](https://github.com/IUCNN/IUCNN/assets/81578981/9a33fabe-b900-403a-9e48-36021f31346d)

**Comment by dsilvestro** [comment]
Hi, the "posterior" column contains the posterior probabilities sampled by the MCMC. you can use programs like [Tracer](https://github.com/beast-dev/tracer) or R packages like [coda](https://cran.r-project.org/package=coda) to calculate summary stats like ESS values. I would generally monitor the posterior and the accuracy columns for convergence.
