### ISSUE TITLE
Error in iucnn_train_model function

### ISSUE THREAD

**Issue by brenaac** [IUCNN/IUCNN#52]
Hi all

I've been trying to run this simple code but I'm stuck on this error:

features <- iucnn_cnn_features(training_occ) # Training features
labels_train <- iucnn_prepare_labels(x = training_labels,
                                     y = features) # Training labels
features_predict <- iucnn_cnn_features(prediction_occ) # Prediction features

m1 <- iucnn_train_model(x = features, lab = labels_train)
> Error in iucnn_train_model(x = features, lab = labels_train) : 
>   Assertion on 'x' failed: Must be of type 'data.frame', not 'cnn_features/list'.

As the iucnn_cnn_features output is a Large cnn_fatures, what should I do?
I tried to covert it into a df, but I got another error related to 'outpath' even though this argument isn't in the function.

Many thanks

**Comment by Orange-chen-PEAR** [comment]
For the features from the iucnn_cnn_features function, you should use the iucnn_cnn_train function.

**Comment by BrunoVilela** [comment]
Hello there! We've recently overhauled the IUCNN package, integrating new spatial packages and implementing substantial changes to the code. If you're still encountering the issue after updating the package to the latest version available on GitHub, could you please share a reproducible code along with the accompanying data? This will enable us to investigate the error more effectively and provide you with a timely resolution. Your cooperation is greatly appreciated!
