### ISSUE TITLE
Error in  iucnn_footprint_features function

### ISSUE THREAD

**Issue by akarolinamoreno** [IUCNN/IUCNN#54]
When I run the iucnn_footprint_features function (using the example), it returns this error:

Downloading Human Footprint data from https://wcshumanfootprint.org/
trying URL 'https://wcshumanfootprint.org/data/HFP1993.zip'
Error in download.file(paste("https://wcshumanfootprint.org/data/HFP",  : 
  cannot open URL 'https://wcshumanfootprint.org/data/HFP1993.zip'
In addition: Warning message:
In download.file(paste("https://wcshumanfootprint.org/data/HFP",  :
  cannot open URL 'https://wcshumanfootprint.org/data/HFP1993.zip': HTTP status was '404 Not Found'
trying URL 'https://wcshumanfootprint.org/data/HFP1993.zip'

**Comment by luannpedro** [comment]
I'm also having this problem

**Comment by BrunoVilela** [comment]
Hello there! We've recently overhauled the IUCNN package, integrating new spatial packages and implementing substantial changes to the code. If you're still encountering the issue after updating the package to the latest version available on GitHub, could you please share a reproducible code along with the accompanying data? This will enable us to investigate the error more effectively and provide you with a timely resolution. Your cooperation is greatly appreciated!

**Comment by weizhii** [comment]
iucnn footprint data page has changed。it is in https://wcshumanfootprint.org/v2，data zip file url now is https://hii-v2-downloads.wcshumanfootprint.org/data/HFP1993.zip and https://hii-v2-downloads.wcshumanfootprint.org/data/HFP2009.zip

**Comment by BrunoVilela** [comment]
Hi there, the updated function now uses geodata::footprint function to download footprint data. It should be working fine.
