### ISSUE TITLE
error installing version 3.0

### ISSUE THREAD

**Issue by luannpedro** [IUCNN/IUCNN#55]
When trying to install the new version of IUCNN 3.0 the following message appears "Error: Failed to install 'IUCNN' from GitHub:
  Missing commas separating Remotes: 'github::azizka/sampbias
  github::xct/rCAT'"

**Comment by weizhii** [comment]
github:xct/rCAT, is gone, not the r package anymore,need comments in the source, and manual compile rCAT in cran site(Google it can find it)

**Comment by BrunoVilela** [comment]
Hello, the package has been update, and this should not be a problem anymore, let us know if you are still having this problem.
